//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCLUOTMUONTHEOTHELOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BCLUOTMUONTHEOTHELOAI()
        {
            this.CT_BCLUOTMUONTHEOTHELOAI = new HashSet<CT_BCLUOTMUONTHEOTHELOAI>();
        }
    
        public int id { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public string MaBaoCao { get; set; }
        public int TongSoLuotMuon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BCLUOTMUONTHEOTHELOAI> CT_BCLUOTMUONTHEOTHELOAI { get; set; }
    }
}
