//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAP
    {
        public int SoPhieuNhap { get; set; }
        public int idSach { get; set; }
        public int DonGia { get; set; }
        public int ThanhTien { get; set; }
        public int SoLuongNhap { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual PHIEUNHAPSACH PHIEUNHAPSACH { get; set; }
    }
}
