//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUONSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUONSACH()
        {
            this.BCSACHTRATREs = new HashSet<BCSACHTRATRE>();
            this.PHIEUMUONTRAs = new HashSet<PHIEUMUONTRA>();
        }
    
        public int id { get; set; }
        public string MaCuonSach { get; set; }
        public int idSach { get; set; }
        public int TinhTrang { get; set; }
        public int DaAn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCSACHTRATRE> BCSACHTRATREs { get; set; }
        public virtual SACH SACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUONTRA> PHIEUMUONTRAs { get; set; }
    }
}
