//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUONTRA
    {
        public int SoPhieuMuonTra { get; set; }
        public int idDocGia { get; set; }
        public int idCuonSach { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public System.DateTime HanTra { get; set; }
        public Nullable<int> SoTienPhat { get; set; }
    
        public virtual CUONSACH CUONSACH { get; set; }
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
