//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int id { get; set; }
        public Nullable<int> TuoiToiThieu { get; set; }
        public Nullable<int> TuoiToiDa { get; set; }
        public Nullable<int> ThoiHanThe { get; set; }
        public Nullable<int> KhoangCachXuatBan { get; set; }
        public Nullable<int> SoSachMuonToiDa { get; set; }
        public Nullable<int> SoNgayMuonToiDa { get; set; }
        public Nullable<int> DonGiaPhat { get; set; }
        public Nullable<int> AD_QDKTTienThu { get; set; }
    }
}
